spring:
  application:
    name: Demo3

  datasource:
      url: jdbc:mysql://localhost:3306/demo3?createDatabaseIfNotExist=true
      username: root
      password: 12345678
  jpa:
    show-sql: true

